export const site = {
  name: {
    first: 'Pablo',
    last: 'Quesada',
  },
  meta: {
    left: 'Portfolio / 2026',
    right: 'Design + Development',
  },
  fragment: 'Make something. Make it better.',
  quote: ['First do it,', 'then do it right,', 'then do it better.'] as const,
  quoteMeta: '02 / Process',
  quoteKicker: 'Process / Iteration / 001',
  about: {
    index: '03 / About',
    statement: ['I design and build', 'digital experiences', 'that move.'] as const,
    role: 'Design + Development',
    discipline: 'Electrical engineering → software',
    intro: [
      'I am a software engineer with a background in electrical engineering. The work starts by existing. Then it gets sharper. Then it gets better.',
      'I treat interfaces as cause and effect — one decision creating the conditions for the next. Precision first. Personality where it counts.',
    ],
  },
  capabilities: [
    { label: 'Creative Development', pips: 3 },
    { label: 'Interaction Design', pips: 2 },
    { label: 'Frontend Development', pips: 4 },
    { label: '3D / WebGL', pips: 2 },
    { label: 'UI / UX', pips: 3 },
    { label: 'Art Direction', pips: 2 },
    { label: 'Motion', pips: 2 },
    { label: 'Branding', pips: 1 },
  ],
  colophon: {
    index: '05 / Colophon',
    heading: 'This website was built with…',
    tools: [
      'Art Direction',
      'Interaction Design',
      '3D',
      'WebGL',
      'Three.js',
      'React',
      'GSAP',
      'Blender',
      'Figma',
      'Frontend Development',
    ],
  },
  contact: {
    index: '06 / Contact',
    headline: ['Start a', 'chain reaction.'] as const,
    email: 'pabloqsd212@gmail.com',
    links: [
      { label: 'Email', href: 'mailto:pabloqsd212@gmail.com' },
      { label: 'GitHub', href: 'https://github.com/pjquesada' },
    ],
  },
  finale: {
    prompt: 'Tap the first tile.',
    done: 'One move creates the next.',
  },
  footer: {
    year: 2026,
    note: 'Chain reaction / 2026',
  },
  nav: [
    { id: 'intro', label: 'Intro', index: '01' },
    { id: 'process', label: 'Process', index: '02' },
    { id: 'about', label: 'About', index: '03' },
    { id: 'work', label: 'Work', index: '04' },
    { id: 'colophon', label: 'Colophon', index: '05' },
    { id: 'contact', label: 'Contact', index: '06' },
  ],
} as const
